/**
 * GENERATED by scripts/theme/sync-radixia.ts from @radixia/brand@1.0.0.
 * Do not edit. Run `pnpm theme:sync` after upgrading the brand package.
 *
 * Radixia's own skin for the census. It is one theme among several and is NOT the
 * default — see neutral.ts for why a fork must not inherit somebody else's
 * identity.
 *
 * `@font-face` uses absolute /fonts/ URLs, which resolve only on an origin that
 * serves them. That is true of www.radixia.ai and false everywhere else, which is
 * the other reason this theme is not the default.
 */

import type { CensusTheme } from "./types.js";

/** The brand release these values were derived from. Asserted by `pnpm theme:sync --check`. */
export const RADIXIA_BRAND_VERSION = "1.0.0";

const FONT_FACES = "@font-face {\n  font-family: \"Fraunces\";\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n  src: url(\"/fonts/fraunces-latin-var.woff2\") format(\"woff2\");\n  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n}\n\n@font-face {\n  font-family: \"Public Sans\";\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n  src: url(\"/fonts/public-sans-latin-var.woff2\") format(\"woff2\");\n  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n}\n\n@font-face {\n  font-family: \"JetBrains Mono\";\n  font-style: normal;\n  font-weight: 100 800;\n  font-display: swap;\n  src: url(\"/fonts/jetbrains-mono-latin-var.woff2\") format(\"woff2\");\n  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;\n}";

/** Radixia's pitch. Kept factual: this is a measurement, not a warning. */
const CTA = {
  "heading": "Would you rather this said something else?",
  "body": "Radixia designs and runs the plumbing that makes a brand reachable by agents: MCP servers, discovery documents, and the boring parts that decide whether any of it can be found. We are in this dataset too.",
  "label": "How we work",
  "url": "https://www.radixia.ai/enterprise-ai"
};

export const RADIXIA_THEME: CensusTheme = {
  id: "radixia",
  // The site writes a manual light/dark override; census pages honour it.
  honourDataTheme: true,
  fontFaces: FONT_FACES,
  tokens: {
    "font-body": "\"Public Sans\", system-ui, sans-serif",
    "font-display": "\"Fraunces\", Georgia, serif",
    "font-mono": "\"JetBrains Mono\", ui-monospace, monospace",
    "paper": "#faf9f7",
    "paper-2": "#f2f0ec",
    "card": "#ffffff",
    "ink": "#1c1a17",
    "ink-2": "#4f4a43",
    "ink-3": "#6f6860",
    "line": "#e4e0d9",
    "accent": "#a8232a",
    "accent-deep": "#7d1a1f",
    "accent-btn": "#a8232a",
    "accent-btn-hover": "#7d1a1f",
    "radius": "10px",
    "radius-btn": "3px",
    "w-max": "960px",
    "ok": "#1b7f4b",
    "warn": "#a86b00",
    "bad": "#9c2b2b",
  },
  darkTokens: {
    "paper": "#191714",
    "paper-2": "#211f1b",
    "card": "#1d1b17",
    "ink": "#eeeae2",
    "ink-2": "#c3bcb0",
    "ink-3": "#9c9488",
    "line": "#37332c",
    "accent": "#d9483c",
    "accent-deep": "#e8897a",
    "accent-btn": "#c02f2a",
    "accent-btn-hover": "#a8232a",
    "ok": "#4fd18b",
    "warn": "#e8b04b",
    "bad": "#ff8f8f",
  },
  branding: {
    productName: "MCP Census",
    operator: { name: "Radixia", url: "https://www.radixia.ai" },
    repoUrl: "https://github.com/radixia/mcp-census",
    // radixia.ai is in this dataset and never excluded from it.
    inOwnDataset: true,
    // The main site serves this and declares it as both icon and apple-touch-icon.
    // /favicon.ico does not exist there, which is what browsers ask for when a page
    // declares nothing, so every census page was logging a 404.
    faviconPath: "/favicon.png",
    cta: CTA,
  },
};
