export {
  AI_CRAWLER_TOKENS,
  AI_CRAWLER_TOKENS_VERSION,
  type AiCrawlerToken,
} from "./config/ai-crawlers.js";
export {
  allowedHttpPaths,
  CANDIDATES_VERSION,
  type CandidateKind,
  CONVENTIONAL_ENDPOINTS,
  CONVENTIONAL_SUBDOMAINS,
  candidatesForCheck,
  DISCOVERY_CANDIDATES,
  type DiscoveryCandidate,
  type Normativity,
  resolveCandidate,
  TEXT_FALLBACKS,
} from "./config/candidates.js";
export {
  CANONICAL_ORIGIN,
  CENSUS_BASE_PATH,
  CENSUS_BASE_URL,
  censusUrl,
  VANITY_DOMAIN,
} from "./config/site.js";
export {
  ALLOWED_JSONRPC_METHODS,
  type AllowedJsonRpcMethod,
  assertCrawlerIdentity,
  assertHttpMethodAllowed,
  assertJsonRpcMethodAllowed,
  assertNoCredentials,
  assertNotOptedOut,
  assertPathAllowed,
  assertRedirectAllowed,
  buildDiscoveryHeaders,
  buildMcpRequestHeaders,
  buildUserAgent,
  CRAWLER_ETHICS_URL,
  type CrawlerIdentity,
  formatUserAgent,
  type GuardRule,
  type HttpMethodContext,
  isWithinApex,
  MCP_PROTOCOL_VERSIONS,
  OPT_OUT_EMAIL,
  POLITENESS,
  ProbeGuardError,
  resolveCrawlerIdentity,
} from "./politeness.js";
export { CENSUS_VERSION, METHODOLOGY_VERSION, SPEC_VERIFIED_ON } from "./version.js";
